[tool.black]
line-length = 88
target_version = ['py39']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 88

[tool.pyright]
include = [
  "bot"
]
exclude = [
  "**/__pycache__",
  "bot_config.py",
  "build",
  "dist",
  "launch_config.py"
]
pythonVersion = "3.9"
