name: Feature Request
description: Suggest a feature to add to the bot application.
labels: Type.Feature-Request
body:
  - type: input
    attributes:
      label: Summary
      description: >
        A short summary of what your feature request is.
    validations:
      required: true
  - type: dropdown
    attributes:
      multiple: false
      label: What is the feature request for?
      options:
        - behaviors/commands
        - codebase
        
    validations:
      required: true
  - type: textarea
    attributes:
      label: The Problem
      description: >
        What problem is your feature trying to solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: The Ideal Solution
      description: >
        What is your ideal solution to the problem?
        How would this feature look like?
    validations:
      required: true
  - type: textarea
    attributes:
      label: The Current Solution
      description: >
        What is the current solution to the problem (if any)?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Any additional information
